//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotnetMvcDbFirst.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class MVCFORM
    {
        public int Id { get; set; }
        public string RollNo { get; set; }
        public string Name { get; set; }
        public string Gender { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public Nullable<int> Class { get; set; }
        public string Address { get; set; }
        public string Transport { get; set; }
        public Nullable<bool> Football { get; set; }
        public Nullable<bool> Kabadi { get; set; }
        public Nullable<bool> Coco { get; set; }
        public Nullable<bool> Cricket { get; set; }
        public string Comments { get; set; }
        public byte[] Photo { get; set; }
    }
}
